cellsociety_team04: controller.SimulationChart Class Reference
controller.SimulationChart Class Reference
Public Member Functions
SimulationChart (Grid g)
void updateDisplay ()
void checkBoundaryAndReset ()
Protected Member Functions
void plotData ()
Private Member Functions
void intializeChart ()
Private Attributes
final int X_AXIS_RANGE = 1000
final int CHART_WIDTH = 500
final int CHART_HEIGHT = 130
final int X_DELTA = 10
final int TICK_MARKS = 4
Grid grid
GridInfo infoSheet
LineChart myLineChart
NumberAxis myXAxis
NumberAxis myYAxis
int myWidth
int myHeight
int myXCoord
List< Series > myDataPoints
Map< Integer, Integer > cellCounts
Detailed Description
Chart that graphs the cell data from the grid
Author
Will Chang
Definition at line 18 of file SimulationChart.java.
Constructor & Destructor Documentation
controller.SimulationChart.SimulationChart (Grid g)
Constructor for the simulation's chart
Parameters
g
Definition at line 41 of file SimulationChart.java.
References controller.Grid.getGridHeight(), controller.Grid.getGridWidth(), and controller.SimulationChart.intializeChart().
Member Function Documentation
void controller.SimulationChart.checkBoundaryAndReset ()
Checks to see if x coordinate has reached the end of the axis
Definition at line 108 of file SimulationChart.java.
Referenced by controller.SimulationChart.updateDisplay().
void controller.SimulationChart.intializeChart () private
Sets up the axes, datapoints, and linechart
Definition at line 54 of file SimulationChart.java.
References controller.GridInfo.getMaxCellState(), controller.SimulationChart.myXAxis, and controller.SimulationChart.myYAxis.
Referenced by controller.SimulationChart.SimulationChart().
void controller.SimulationChart.plotData () protected
Gets cellcounts from grid and plots it in the Chart
Definition at line 97 of file SimulationChart.java.
References controller.Grid.getCellCounts(), and controller.SimulationChart.X_DELTA.
Referenced by controller.SimulationChart.updateDisplay().
void controller.SimulationChart.updateDisplay ()
Checks if the data has reached the length of the graph, plots new datapoints each step
Definition at line 89 of file SimulationChart.java.
References controller.SimulationChart.checkBoundaryAndReset(), and controller.SimulationChart.plotData().
Referenced by controller.MainController.stepSimulation().
Member Data Documentation
Map<Integer, Integer> controller.SimulationChart.cellCounts private
Definition at line 35 of file SimulationChart.java.
final int controller.SimulationChart.CHART_HEIGHT = 130 private
Definition at line 22 of file SimulationChart.java.
final int controller.SimulationChart.CHART_WIDTH = 500 private
Definition at line 21 of file SimulationChart.java.
Grid controller.SimulationChart.grid private
Definition at line 26 of file SimulationChart.java.
GridInfo controller.SimulationChart.infoSheet private
Definition at line 27 of file SimulationChart.java.
List<Series> controller.SimulationChart.myDataPoints private
Definition at line 34 of file SimulationChart.java.
int controller.SimulationChart.myHeight private
Definition at line 32 of file SimulationChart.java.
LineChart controller.SimulationChart.myLineChart private
Definition at line 28 of file SimulationChart.java.
int controller.SimulationChart.myWidth private
Definition at line 31 of file SimulationChart.java.
NumberAxis controller.SimulationChart.myXAxis private
Definition at line 29 of file SimulationChart.java.
Referenced by controller.SimulationChart.intializeChart().
int controller.SimulationChart.myXCoord private
Definition at line 33 of file SimulationChart.java.
NumberAxis controller.SimulationChart.myYAxis private
Definition at line 30 of file SimulationChart.java.
Referenced by controller.SimulationChart.intializeChart().
final int controller.SimulationChart.TICK_MARKS = 4 private
Definition at line 24 of file SimulationChart.java.
final int controller.SimulationChart.X_AXIS_RANGE = 1000 private
Definition at line 20 of file SimulationChart.java.
final int controller.SimulationChart.X_DELTA = 10 private
Definition at line 23 of file SimulationChart.java.
Referenced by controller.SimulationChart.plotData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/SimulationChart.java