cellsociety_team04: simulationObjects.PatchBodyTriangle Class Reference
simulationObjects.PatchBodyTriangle Class Reference
Public Member Functions
PatchBodyTriangle (int x, int y, double gridPixelHeight, double gridPixelWidth, int gridHeight, int gridWidth)
void buildBody ()
Public Member Functions inherited from simulationObjects.PatchBody
PatchBody (int x, int y)
abstract void buildBody ()
void createPolyFromPoints (Double[] pts)
Point getCenter ()
int getPatchHeight ()
int getPatchWidth ()
void setCenter (Point c)
void setPatchHeight (int h)
void setPatchWidth (int w)
Additional Inherited Members
Public Attributes inherited from simulationObjects.PatchBody
int myX
int myY
Protected Attributes inherited from simulationObjects.PatchBody
GridInfo infoSheet = new GridInfo()
Detailed Description
triangle implementation of patch body
Author
Davis
Definition at line 12 of file PatchBodyTriangle.java.
Constructor & Destructor Documentation
simulationObjects.PatchBodyTriangle.PatchBodyTriangle (int x, int y, double gridPixelHeight, double gridPixelWidth, int gridHeight, int gridWidth)
Definition at line 14 of file PatchBodyTriangle.java.
References simulationObjects.PatchBodyTriangle.buildBody(), simulationObjects.PatchBody.setPatchHeight(), and simulationObjects.PatchBody.setPatchWidth().
Member Function Documentation
void simulationObjects.PatchBodyTriangle.buildBody ()
Definition at line 23 of file PatchBodyTriangle.java.
References simulationObjects.PatchBody.createPolyFromPoints(), simulationObjects.PatchBody.getPatchHeight(), simulationObjects.PatchBody.getPatchWidth(), simulationObjects.PatchBody.myX, simulationObjects.PatchBody.myY, and simulationObjects.PatchBody.setCenter().
Referenced by simulationObjects.PatchBodyTriangle.PatchBodyTriangle().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/PatchBodyTriangle.java