cellsociety_team04: simulationObjects.Patch Class Reference
simulationObjects.Patch Class Reference
Classes
enum relativePosition
enum State
Public Member Functions
Patch ()
Patch (int x, int y, Grid m)
void addCell (Cell cell)
void createBody (int bodyType)
Cell getCell ()
int getGridX ()
int getGridY ()
void getNeighbors ()
int getPreviousState ()
int getState ()
void initialize (int x, int y, Grid m)
boolean isEmpty ()
void prepareToUpdate ()
Patch getRandomEmptyPatch ()
void removeCell ()
void setCellClass (Class<?> c)
void setColorToBody (Color myColor)
void setPreviousState (int myState)
void toggleCellState ()
void update ()
void updateCellConstraints (Cell cell)
Protected Attributes
Cell myCell
int xCoord
int yCoord
Grid grid
List< Patch > myNeighbors
Image image
ImageView myView
State myState
PatchBody myBody
GridInfo infoSheet
Private Member Functions
void createNewCell ()
Private Attributes
Class<?> myCellClass
int myPreviousCellState
Detailed Description
Patch for the simulation. Holds locations, cells, and simulation rules
Author
Will Chang
Definition at line 17 of file Patch.java.
Constructor & Destructor Documentation
simulationObjects.Patch.Patch ()
Constructors
Definition at line 47 of file Patch.java.
simulationObjects.Patch.Patch (int x, int y, Grid m)
Definition at line 52 of file Patch.java.
References simulationObjects.Patch.initialize().
Member Function Documentation
void simulationObjects.Patch.addCell (Cell cell)
Adds cell along with GUI info.
Parameters
cell to occupy patch
Definition at line 63 of file Patch.java.
References simulationObjects.Patch.State.OCCUPIED, simulationObjects.Patch.removeCell(), and simulationObjects.Patch.updateCellConstraints().
Referenced by simulationObjects.Patch.createNewCell(), controller.MainController.initializeSimulationObjects(), simulationObjects.PredatorCell.leaveEgg(), simulationObjects.SugarCell.makeMove(), simulationObjects.PredatorCell.makeMove(), simulationObjects.LifePatch.toggleCellState(), simulationObjects.LifePatch.update(), and simulationObjects.SegCell.update().
void simulationObjects.Patch.createBody (int bodyType)
creates a patch body for the patch
Parameters
bodyType what kind of shape it is
Definition at line 79 of file Patch.java.
References controller.Grid.getGridHeight(), controller.Grid.getGridWidth(), and simulationObjects.Patch.updateCellConstraints().
Referenced by controller.Grid.addPatchToGrid().
void simulationObjects.Patch.createNewCell () private
create a new cell and assign it to this patch new cell comes from the cell class stored in this patch
Definition at line 111 of file Patch.java.
References simulationObjects.Patch.addCell(), simulationObjects.Cell.setState(), simulationObjects.Cell.setX(), and simulationObjects.Cell.setY().
Referenced by simulationObjects.Patch.toggleCellState().
Cell simulationObjects.Patch.getCell ()
Gets the cell
Returns
myCell
Definition at line 127 of file Patch.java.
References simulationObjects.Patch.myCell.
Referenced by controller.Grid.countCellInPatch(), and simulationObjects.SegCell.isSatisfied().
int simulationObjects.Patch.getGridX ()
Definition at line 131 of file Patch.java.
References simulationObjects.Patch.xCoord.
Referenced by controller.Grid.addPatchAtPoint(), and simulationObjects.PredatorCell.leaveEgg().
int simulationObjects.Patch.getGridY ()
Definition at line 135 of file Patch.java.
References simulationObjects.Patch.yCoord.
Referenced by controller.Grid.addPatchAtPoint(), and simulationObjects.PredatorCell.leaveEgg().
void simulationObjects.Patch.getNeighbors ()
Returns surrounding Patches
Definition at line 142 of file Patch.java.
References controller.Grid.getNeighborsAround().
int simulationObjects.Patch.getPreviousState ()
Definition at line 146 of file Patch.java.
References simulationObjects.Patch.myPreviousCellState.
Patch simulationObjects.Patch.getRandomEmptyPatch ()
Definition at line 187 of file Patch.java.
References controller.Grid.findEmptyPatch().
Referenced by simulationObjects.SegCell.update().
int simulationObjects.Patch.getState ()
Definition at line 151 of file Patch.java.
Referenced by simulationObjects.AntCell.returnToNest().
void simulationObjects.Patch.initialize (int x, int y, Grid m)
For Special patch simulations.
Parameters
x loc
y loc
m manager
Definition at line 165 of file Patch.java.
References simulationObjects.Patch.State.EMPTY.
Referenced by controller.PatchFactory.createPatch(), and simulationObjects.Patch.Patch().
boolean simulationObjects.Patch.isEmpty ()
Definition at line 173 of file Patch.java.
Referenced by controller.Grid.countCellInPatch(), simulationObjects.LifePatch.processNeighborsAndUpdateState(), and simulationObjects.PredatorCell.updateStatesandMakeMoves().
void simulationObjects.Patch.prepareToUpdate ()
Sets up the update
Definition at line 180 of file Patch.java.
References simulationObjects.Cell.prepareToUpdate().
void simulationObjects.Patch.removeCell ()
Definition at line 192 of file Patch.java.
References simulationObjects.Patch.State.EMPTY.
Referenced by simulationObjects.Patch.addCell(), simulationObjects.PredatorCell.feed(), simulationObjects.SugarCell.makeMove(), simulationObjects.PredatorCell.makeMove(), controller.Grid.removeCellinPatch(), simulationObjects.LifePatch.toggleCellState(), simulationObjects.Patch.toggleCellState(), simulationObjects.LifePatch.update(), simulationObjects.SugarPatch.update(), simulationObjects.SegCell.update(), and simulationObjects.Patch.update().
void simulationObjects.Patch.setCellClass (Class<?> c)
Definition at line 200 of file Patch.java.
Referenced by controller.MainController.initializeSimulationObjects().
void simulationObjects.Patch.setColorToBody (Color myColor)
Definition at line 204 of file Patch.java.
void simulationObjects.Patch.setPreviousState (int myState)
Definition at line 208 of file Patch.java.
References simulationObjects.Patch.myState.
Referenced by simulationObjects.ForestCell.prepareToUpdate().
void simulationObjects.Patch.toggleCellState ()
Definition at line 212 of file Patch.java.
References simulationObjects.Patch.createNewCell(), simulationObjects.Cell.getNextState(), simulationObjects.Patch.removeCell(), and simulationObjects.Cell.setState().
Referenced by controller.MainController.toggleCellStateForMouseEvent().
void simulationObjects.Patch.update ()
Updates patch and the cell
Definition at line 228 of file Patch.java.
References simulationObjects.Cell.getState(), simulationObjects.Patch.removeCell(), and simulationObjects.Cell.update().
void simulationObjects.Patch.updateCellConstraints (Cell cell)
Definition at line 240 of file Patch.java.
References simulationObjects.PatchBody.getCenter(), simulationObjects.PatchBody.getPatchHeight(), and simulationObjects.PatchBody.getPatchWidth().
Referenced by simulationObjects.Patch.addCell(), simulationObjects.SugarPatch.createBody(), and simulationObjects.Patch.createBody().
Member Data Documentation
Grid simulationObjects.Patch.grid protected
Definition at line 30 of file Patch.java.
Referenced by simulationObjects.SugarPatch.createBody(), and simulationObjects.SugarPatch.getNeighbors().
Image simulationObjects.Patch.image protected
Definition at line 32 of file Patch.java.
GridInfo simulationObjects.Patch.infoSheet protected
Definition at line 38 of file Patch.java.
Referenced by simulationObjects.SugarPatch.setColorToBody().
PatchBody simulationObjects.Patch.myBody protected
Definition at line 36 of file Patch.java.
Referenced by simulationObjects.SugarPatch.createBody(), and simulationObjects.SugarPatch.setColorToBody().
Cell simulationObjects.Patch.myCell protected
Definition at line 27 of file Patch.java.
Referenced by simulationObjects.SugarPatch.createBody(), simulationObjects.Patch.getCell(), and simulationObjects.SugarPatch.update().
Class<?> simulationObjects.Patch.myCellClass private
Definition at line 40 of file Patch.java.
List<Patch> simulationObjects.Patch.myNeighbors protected
Definition at line 31 of file Patch.java.
Referenced by simulationObjects.LifePatch.countNeighbors(), simulationObjects.SugarPatch.getNeighbors(), and simulationObjects.SugarPatch.update().
int simulationObjects.Patch.myPreviousCellState private
Definition at line 42 of file Patch.java.
Referenced by simulationObjects.Patch.getPreviousState().
State simulationObjects.Patch.myState protected
Definition at line 34 of file Patch.java.
Referenced by simulationObjects.LifePatch.processNeighborsAndUpdateState(), simulationObjects.Patch.setPreviousState(), simulationObjects.LifePatch.toggleCellState(), and simulationObjects.LifePatch.update().
ImageView simulationObjects.Patch.myView protected
Definition at line 33 of file Patch.java.
int simulationObjects.Patch.xCoord protected
Definition at line 28 of file Patch.java.
Referenced by simulationObjects.SugarPatch.createBody(), simulationObjects.Patch.getGridX(), simulationObjects.SugarPatch.getNeighbors(), simulationObjects.LifePatch.toggleCellState(), and simulationObjects.LifePatch.update().
int simulationObjects.Patch.yCoord protected
Definition at line 29 of file Patch.java.
Referenced by simulationObjects.SugarPatch.createBody(), simulationObjects.Patch.getGridY(), simulationObjects.SugarPatch.getNeighbors(), simulationObjects.LifePatch.toggleCellState(), and simulationObjects.LifePatch.update().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/Patch.java