cellsociety_team04: controller.ToroidalEdgeRules Class Reference
controller.ToroidalEdgeRules Class Reference
Public Member Functions
ToroidalEdgeRules (int x, int y, Grid g)
void applyRulesAndGetNeighbors (int nextX, int nextY, List< Patch > neighbors)
Public Member Functions inherited from controller.GridEdgeRules
GridEdgeRules (int x, int y, Grid g)
abstract void applyRulesAndGetNeighbors (int nextX, int nextY, List< Patch > neighbors)
boolean isOutOfBounds (int xCoord, int yCoord)
Private Member Functions
int wrapCoordAround (int coord, int max)
Additional Inherited Members
Protected Attributes inherited from controller.GridEdgeRules
int myXBound
int myYBound
Grid grid
Detailed Description
Toroidal grid rules
Author
Will Chang
Definition at line 13 of file ToroidalEdgeRules.java.
Constructor & Destructor Documentation
controller.ToroidalEdgeRules.ToroidalEdgeRules (int x, int y, Grid g)
Definition at line 15 of file ToroidalEdgeRules.java.
Member Function Documentation
void controller.ToroidalEdgeRules.applyRulesAndGetNeighbors (int nextX, int nextY, List< Patch > neighbors)
Sets up the Toroidal edge rules
Definition at line 23 of file ToroidalEdgeRules.java.
References controller.Grid.getPatchAtPoint(), controller.GridEdgeRules.grid, controller.GridEdgeRules.isOutOfBounds(), controller.GridEdgeRules.myXBound, controller.GridEdgeRules.myYBound, and controller.ToroidalEdgeRules.wrapCoordAround().
int controller.ToroidalEdgeRules.wrapCoordAround (int coord, int max) private
Wraps a coordinate around the edges of the grid.
Parameters
coord out of bounds coordinate to wrap around
max boundary reference
Returns
the wrapped around coordinate
Definition at line 43 of file ToroidalEdgeRules.java.
Referenced by controller.ToroidalEdgeRules.applyRulesAndGetNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/ToroidalEdgeRules.java