cellsociety_team04: controller.GridInfo Class Reference
controller.GridInfo Class Reference
Public Member Functions
int getAdjacentType ()
String getCellType ()
Color getColor (String stateType)
int getHeight ()
int getMaxCellState ()
double getParam ()
String getPatchType ()
List< String > getStateTypes ()
int getWidth ()
List< Integer > getParamList ()
void setAdjacent (int adjacent)
void setColor (String stateType, Color myColor)
void setHeight (int height)
void setMaxCellState (int state)
void setParameter (double d)
void setPatchType (String type)
void setStateTypes (List< String > stateTypes)
void setType (String type)
void setWidth (int width)
void setParamList (String content)
Public Attributes
boolean useGivenGrid = true
Static Private Attributes
static int myWidth = -1
static int myHeight = -1
static String myType
static String myPatchType = "Default"
static int myAdjacentType = 8
static double myParameter = 0.7
static HashMap< String, Color > stateColors = new HashMap<String, Color>()
static List< String > myStateTypes
static int maxCellState
static List< Integer > paramList = new ArrayList<>()
Detailed Description
Stores the parameter and info for the grid
Author
Viddamao
Definition at line 16 of file GridInfo.java.
Member Function Documentation
int controller.GridInfo.getAdjacentType ()
Definition at line 29 of file GridInfo.java.
References controller.GridInfo.myAdjacentType.
Referenced by controller.Grid.getNeighborsAround().
String controller.GridInfo.getCellType ()
Definition at line 33 of file GridInfo.java.
References controller.GridInfo.myType.
Referenced by controller.MainController.initializeSimulationObjects(), controller.Parser.inputValidion(), and controller.Parser.setCellStates().
Color controller.GridInfo.getColor (String stateType)
Definition at line 37 of file GridInfo.java.
Referenced by controller.ColorPicker.buildColorPickerMenu(), simulationObjects.LifeCell.LifeCell(), simulationObjects.PredatorCell.PredatorCell(), simulationObjects.SugarPatch.setColorToBody(), simulationObjects.ForestCell.setState(), simulationObjects.SegCell.setState(), simulationObjects.SugarCell.setState(), simulationObjects.PredatorCell.setState(), and simulationObjects.SugarCell.SugarCell().
int controller.GridInfo.getHeight ()
Definition at line 41 of file GridInfo.java.
References controller.GridInfo.myHeight.
Referenced by controller.MainController.randomizeGrid(), and controller.MainController.setupGridConstraints().
int controller.GridInfo.getMaxCellState ()
Definition at line 45 of file GridInfo.java.
References controller.GridInfo.maxCellState.
Referenced by controller.Grid.initializeCellCounts(), and controller.SimulationChart.intializeChart().
double controller.GridInfo.getParam ()
Definition at line 49 of file GridInfo.java.
References controller.GridInfo.myParameter.
Referenced by simulationObjects.ForestCell.willCatchFire().
List<Integer> controller.GridInfo.getParamList ()
Definition at line 66 of file GridInfo.java.
References controller.GridInfo.paramList.
Referenced by simulationObjects.Cell.Cell().
String controller.GridInfo.getPatchType ()
Definition at line 53 of file GridInfo.java.
References controller.GridInfo.myPatchType.
Referenced by controller.PatchFactory.createPatch().
List<String> controller.GridInfo.getStateTypes ()
Definition at line 58 of file GridInfo.java.
References controller.GridInfo.myStateTypes.
Referenced by controller.ColorPicker.buildColorPickerMenu(), and controller.ColorPicker.showColorPicker().
int controller.GridInfo.getWidth ()
Definition at line 62 of file GridInfo.java.
References controller.GridInfo.myWidth.
Referenced by controller.MainController.randomizeGrid(), and controller.MainController.setupGridConstraints().
void controller.GridInfo.setAdjacent (int adjacent)
Definition at line 71 of file GridInfo.java.
Referenced by controller.Parser.attributeParse().
void controller.GridInfo.setColor (String stateType, Color myColor)
Definition at line 76 of file GridInfo.java.
Referenced by controller.ColorPicker.buildColorPickerMenu(), and controller.Parser.setCellStates().
void controller.GridInfo.setHeight (int height)
Definition at line 80 of file GridInfo.java.
Referenced by controller.Parser.attributeParse(), and controller.MainController.setupGridConstraints().
void controller.GridInfo.setMaxCellState (int state)
Definition at line 84 of file GridInfo.java.
Referenced by controller.Parser.attributeParse().
void controller.GridInfo.setParameter (double d)
Definition at line 88 of file GridInfo.java.
Referenced by controller.Parser.attributeParse().
void controller.GridInfo.setParamList (String content)
Definition at line 110 of file GridInfo.java.
Referenced by controller.Parser.attributeParse().
void controller.GridInfo.setPatchType (String type)
Definition at line 92 of file GridInfo.java.
Referenced by controller.Parser.attributeParse().
void controller.GridInfo.setStateTypes (List< String > stateTypes)
Definition at line 97 of file GridInfo.java.
Referenced by controller.Parser.setCellStates().
void controller.GridInfo.setType (String type)
Definition at line 101 of file GridInfo.java.
Referenced by controller.Parser.attributeParse().
void controller.GridInfo.setWidth (int width)
Definition at line 106 of file GridInfo.java.
Referenced by controller.Parser.attributeParse(), and controller.MainController.setupGridConstraints().
Member Data Documentation
int controller.GridInfo.maxCellState static private
Definition at line 25 of file GridInfo.java.
Referenced by controller.GridInfo.getMaxCellState().
int controller.GridInfo.myAdjacentType = 8 static private
Definition at line 21 of file GridInfo.java.
Referenced by controller.GridInfo.getAdjacentType().
int controller.GridInfo.myHeight = -1 static private
Definition at line 18 of file GridInfo.java.
Referenced by controller.GridInfo.getHeight().
double controller.GridInfo.myParameter = 0.7 static private
Definition at line 22 of file GridInfo.java.
Referenced by controller.GridInfo.getParam().
String controller.GridInfo.myPatchType = "Default" static private
Definition at line 20 of file GridInfo.java.
Referenced by controller.GridInfo.getPatchType().
List<String> controller.GridInfo.myStateTypes static private
Definition at line 24 of file GridInfo.java.
Referenced by controller.GridInfo.getStateTypes().
String controller.GridInfo.myType static private
Definition at line 19 of file GridInfo.java.
Referenced by controller.GridInfo.getCellType().
int controller.GridInfo.myWidth = -1 static private
Definition at line 17 of file GridInfo.java.
Referenced by controller.GridInfo.getWidth().
List<Integer> controller.GridInfo.paramList = new ArrayList<>() static private
Definition at line 26 of file GridInfo.java.
Referenced by controller.GridInfo.getParamList().
HashMap<String, Color> controller.GridInfo.stateColors = new HashMap<String, Color>() static private
Definition at line 23 of file GridInfo.java.
boolean controller.GridInfo.useGivenGrid = true
Definition at line 27 of file GridInfo.java.
Referenced by controller.MainController.setupGridConstraints().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/GridInfo.java