cellsociety_team04: controller.UserInterface Class Reference
controller.UserInterface Class Reference
Public Member Functions
UserInterface (Stage s, MainController mainController)
void addNode (Node n)
Pane getRootPane ()
void removeNode (Node n)
void reset ()
void setChart (SimulationChart chart)
void setGrid (Grid grid)
Static Public Attributes
static final int GRID_WIDTH = 500
static final int GRID_HEIGHT = 500
Private Member Functions
Button createButton (String title, int posX, int posY, EventHandler< ActionEvent > handler)
RadioButton createRadioButton (String title, int posX, int posY, ToggleGroup group, EventHandler< ActionEvent > handler)
Slider createSlider (int start, int stop, double startVal, int posX, int posY, ChangeListener< Number > listener)
double doubleFromResource (String s)
Integer intFromResource (String s)
void makeBottomPanel ()
Private Attributes
MainController myMainController
Grid myGrid
Pane myRootPane
Stage myStage
SimulationChart myChart
Static Private Attributes
static ResourceBundle ourMessages
static final int PANEL_HEIGHT = 200
Detailed Description
The UI of the application, handles buttons and handlers as well as the scene
Author
Davis
Definition at line 28 of file UserInterface.java.
Constructor & Destructor Documentation
controller.UserInterface.UserInterface (Stage s, MainController mainController)
Definition at line 39 of file UserInterface.java.
References controller.UserInterface.makeBottomPanel().
Member Function Documentation
void controller.UserInterface.addNode (Node n)
add a node to the pane
Parameters
n node to add
Definition at line 60 of file UserInterface.java.
Referenced by controller.MainController.createGrid().
Button controller.UserInterface.createButton (String title, int posX, int posY, EventHandler< ActionEvent > handler) private
create a button
Parameters
title title of the button
posX x position of button
posY y position of button
handler action handler
Returns
the button
Definition at line 77 of file UserInterface.java.
Referenced by controller.UserInterface.makeBottomPanel().
RadioButton controller.UserInterface.createRadioButton (String title, int posX, int posY, ToggleGroup group, EventHandler< ActionEvent > handler) private
create a radiobutton
Parameters
title title of the radiobutton
posX x position of radiobutton
posY y position of radiobutton
handler action handler
Returns
the radiobutton
Definition at line 99 of file UserInterface.java.
Referenced by controller.UserInterface.makeBottomPanel().
Slider controller.UserInterface.createSlider (int start, int stop, double startVal, int posX, int posY, ChangeListener< Number > listener) private
create a slider
Parameters
start minimum value of the slider
stop maximum value of the slider
startVal initial value of the slider
posX x position of the slider
posY y position of the slider
listener listener for when the slider value changes
Returns
the slider
Definition at line 127 of file UserInterface.java.
Referenced by controller.UserInterface.makeBottomPanel().
double controller.UserInterface.doubleFromResource (String s) private
returns a double value from the resource file given a key
Parameters
s key to find in the resource file
Returns
double from resource file
Definition at line 143 of file UserInterface.java.
Referenced by controller.UserInterface.intFromResource(), and controller.UserInterface.makeBottomPanel().
Pane controller.UserInterface.getRootPane ()
Returns
the rootPane for adding children
Definition at line 150 of file UserInterface.java.
References controller.UserInterface.myRootPane.
Integer controller.UserInterface.intFromResource (String s) private
returns an integer value from the resource file given a key
Parameters
s key to find in the resource file
Returns
integer from resource file
Definition at line 161 of file UserInterface.java.
References controller.UserInterface.doubleFromResource().
Referenced by controller.UserInterface.makeBottomPanel().
void controller.UserInterface.makeBottomPanel () private
create the bottom panel that the user interacts with all UI element's coordinates are pulled from the resource file
Definition at line 169 of file UserInterface.java.
References controller.Grid.changeRulesTo(), controller.UserInterface.createButton(), controller.UserInterface.createRadioButton(), controller.UserInterface.createSlider(), controller.UserInterface.doubleFromResource(), controller.Grid.getGridHeight(), controller.Grid.getGridWidth(), controller.MainController.initializeSimulationWithData(), controller.UserInterface.intFromResource(), controller.UserInterface.myGrid, controller.Grid.setPatchBody(), controller.MainController.setSimulationSpeed(), controller.ColorPicker.showColorPicker(), controller.MainController.startSimulation(), controller.MainController.stepSimulation(), and controller.MainController.stopSimulation().
Referenced by controller.UserInterface.reset(), and controller.UserInterface.UserInterface().
void controller.UserInterface.removeNode (Node n)
remove a node from the pane
Parameters
n node to add
Definition at line 347 of file UserInterface.java.
Referenced by controller.MainController.createGrid().
void controller.UserInterface.reset ()
Definition at line 351 of file UserInterface.java.
References controller.UserInterface.makeBottomPanel().
Referenced by controller.MainController.initializeSimulationWithData().
void controller.UserInterface.setChart (SimulationChart chart)
Definition at line 356 of file UserInterface.java.
Referenced by controller.MainController.initializeSimulationObjects().
void controller.UserInterface.setGrid (Grid grid)
Definition at line 361 of file UserInterface.java.
Referenced by controller.MainController.initializeSimulationObjects().
Member Data Documentation
final int controller.UserInterface.GRID_HEIGHT = 500 static
Definition at line 30 of file UserInterface.java.
Referenced by controller.MainController.createGrid().
final int controller.UserInterface.GRID_WIDTH = 500 static
Definition at line 29 of file UserInterface.java.
Referenced by controller.MainController.createGrid().
SimulationChart controller.UserInterface.myChart private
Definition at line 37 of file UserInterface.java.
Grid controller.UserInterface.myGrid private
Definition at line 34 of file UserInterface.java.
Referenced by controller.UserInterface.makeBottomPanel().
MainController controller.UserInterface.myMainController private
Definition at line 33 of file UserInterface.java.
Pane controller.UserInterface.myRootPane private
Definition at line 35 of file UserInterface.java.
Referenced by controller.UserInterface.getRootPane().
Stage controller.UserInterface.myStage private
Definition at line 36 of file UserInterface.java.
ResourceBundle controller.UserInterface.ourMessages static private
Definition at line 31 of file UserInterface.java.
final int controller.UserInterface.PANEL_HEIGHT = 200 static private
Definition at line 32 of file UserInterface.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/UserInterface.java