cellsociety_team04: controller.Parser Class Reference
controller.Parser Class Reference
Static Public Member Functions
static List parserXml (String fileName) throws Exception
Static Package Attributes
static GridInfo infoSheet = new GridInfo()
Static Private Member Functions
static void attributeParse (List< GridRows > cellList, Node node, boolean flag)
static void inputValidion ()
static void setCellStates ()
Static Private Attributes
static ResourceBundle messages
Detailed Description
Parameters
filename String input for the xml file name
xml parser for the input grid
return a list of cell nodes needs first process to grid
Definition at line 32 of file Parser.java.
Member Function Documentation
static void controller.Parser.attributeParse (List< GridRows > cellList, Node node, boolean flag) static private
Parameters
cellList return a list of strings with rows in the grid
node the input node in XML
flag magic number
Definition at line 47 of file Parser.java.
References controller.GridRows.id, controller.Parser.infoSheet, controller.GridInfo.setAdjacent(), controller.GridInfo.setHeight(), controller.GridInfo.setMaxCellState(), controller.GridInfo.setParameter(), controller.GridInfo.setParamList(), controller.GridInfo.setPatchType(), controller.GridInfo.setType(), controller.GridInfo.setWidth(), and controller.GridRows.states.
Referenced by controller.Parser.parserXml().
static void controller.Parser.inputValidion () static private
Definition at line 103 of file Parser.java.
References controller.GridInfo.getCellType(), controller.Parser.infoSheet, and controller.Parser.messages.
Referenced by controller.Parser.parserXml().
static List controller.Parser.parserXml (String fileName) throws Exception static
Definition at line 112 of file Parser.java.
References controller.Parser.attributeParse(), controller.Parser.inputValidion(), controller.Parser.messages, and controller.Parser.setCellStates().
Referenced by controller.MainController.initializeSimulationWithData().
static void controller.Parser.setCellStates () static private
Definition at line 159 of file Parser.java.
References controller.GridInfo.getCellType(), simulationObjects.Cell.getInitialColors(), simulationObjects.Cell.getStateTypes(), controller.Parser.infoSheet, controller.Parser.messages, controller.GridInfo.setColor(), and controller.GridInfo.setStateTypes().
Referenced by controller.Parser.parserXml().
Member Data Documentation
GridInfo controller.Parser.infoSheet = new GridInfo() static package
Definition at line 182 of file Parser.java.
Referenced by controller.Parser.attributeParse(), controller.Parser.inputValidion(), and controller.Parser.setCellStates().
ResourceBundle controller.Parser.messages static private
Definition at line 184 of file Parser.java.
Referenced by controller.Parser.inputValidion(), controller.Parser.parserXml(), and controller.Parser.setCellStates().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/Parser.java