cellsociety_team04: controller.MainController Class Reference
controller.MainController Class Reference
Public Member Functions
void initializeSimulationWithData (File XMLData)
void setSimulationSpeed (double speed, boolean play)
void start (Stage s) throws Exception
void startSimulation ()
void stepSimulation ()
void stopSimulation ()
Static Public Member Functions
static void main (String[] args) throws Exception
Protected Member Functions
Cell createCell (int i, int j, int state, Class<?> cellClass) throws InstantiationException, IllegalAccessException
void createPopulationChart (int width, int height)
Private Member Functions
void createGrid (int width, int height)
void initializeSimulationObjects (List< GridRows > gridRows)
List< GridRows > randomizeGrid ()
void setupGridConstraints (List< GridRows > gridRows)
void toggleCellStateForMouseEvent (MouseEvent mouseEvent)
Private Attributes
UserInterface myUserInterface
Timeline myAnimation
Grid myGrid
GridInfo myInfoSheet = new GridInfo()
SimulationChart myChart
int myGridWidth
int myGridHeight
EventHandler< ActionEvent > oneFrame
Static Private Attributes
static ResourceBundle ourProperties
static final double DEFAULT_SPEED = .1
static final int DEFAULT_WIDTH = 10
static final int DEFAULT_HEIGHT = 10
Detailed Description
The main controller responsible for the gameloop, as well as creating instances of the user interface and grid
Author
Davis Gossage
Definition at line 30 of file MainController.java.
Member Function Documentation
Cell controller.MainController.createCell (int i, int j, int state, Class<?> cellClass) throws InstantiationException, IllegalAccessException protected
Definition at line 60 of file MainController.java.
References simulationObjects.Cell.setState(), simulationObjects.Cell.setX(), and simulationObjects.Cell.setY().
Referenced by controller.MainController.initializeSimulationObjects().
void controller.MainController.createGrid (int width, int height) private
create an instance of the grid set column and row constraints and add to the scene
Parameters
width width of the grid
height height of the grid
Definition at line 79 of file MainController.java.
References controller.UserInterface.addNode(), controller.UserInterface.GRID_HEIGHT, controller.UserInterface.GRID_WIDTH, controller.UserInterface.removeNode(), and controller.MainController.toggleCellStateForMouseEvent().
Referenced by controller.MainController.initializeSimulationObjects().
void controller.MainController.createPopulationChart (int width, int height) protected
Definition at line 97 of file MainController.java.
void controller.MainController.initializeSimulationObjects (List< GridRows > gridRows) private
take the data array given by the parser and create patches and cell objects
Parameters
gridRows list given by the parser
Definition at line 110 of file MainController.java.
References simulationObjects.Patch.addCell(), controller.Grid.addPatchAtPoint(), controller.MainController.createCell(), controller.MainController.createGrid(), controller.PatchFactory.createPatch(), controller.GridInfo.getCellType(), controller.Grid.initializeCellCounts(), controller.MainController.myGridHeight, controller.MainController.myGridWidth, simulationObjects.Patch.setCellClass(), controller.UserInterface.setChart(), controller.UserInterface.setGrid(), controller.MainController.setupGridConstraints(), and controller.Grid.updateAllNeighborhoods().
Referenced by controller.MainController.initializeSimulationWithData().
void controller.MainController.initializeSimulationWithData (File XMLData)
parse the XMLData and check for exceptions
Parameters
XMLData data to parse
Definition at line 171 of file MainController.java.
References controller.MainController.initializeSimulationObjects(), controller.Parser.parserXml(), controller.UserInterface.reset(), and controller.MainController.stopSimulation().
Referenced by controller.UserInterface.makeBottomPanel().
static void controller.MainController.main (String[] args) throws Exception static
Definition at line 31 of file MainController.java.
References controller.MainController.ourProperties.
List<GridRows> controller.MainController.randomizeGrid () private
Definition at line 189 of file MainController.java.
References controller.GridInfo.getHeight(), controller.GridInfo.getWidth(), controller.GridRows.id, and controller.GridRows.states.
Referenced by controller.MainController.setupGridConstraints().
void controller.MainController.setSimulationSpeed (double speed, boolean play)
change the simulation speed
Parameters
speed speed of the simulation
play whether the animation should play after the speed change
Definition at line 216 of file MainController.java.
References controller.MainController.oneFrame.
Referenced by controller.UserInterface.makeBottomPanel(), and controller.MainController.start().
void controller.MainController.setupGridConstraints (List< GridRows > gridRows) private
Definition at line 231 of file MainController.java.
References controller.MainController.DEFAULT_HEIGHT, controller.MainController.DEFAULT_WIDTH, controller.GridInfo.getHeight(), controller.GridInfo.getWidth(), controller.MainController.randomizeGrid(), controller.GridInfo.setHeight(), controller.GridInfo.setWidth(), and controller.GridInfo.useGivenGrid.
Referenced by controller.MainController.initializeSimulationObjects().
void controller.MainController.start (Stage s) throws Exception
Definition at line 260 of file MainController.java.
References controller.MainController.setSimulationSpeed().
void controller.MainController.startSimulation ()
starts the simulation
Definition at line 269 of file MainController.java.
Referenced by controller.UserInterface.makeBottomPanel().
void controller.MainController.stepSimulation ()
increment the simulation by one frame
Definition at line 279 of file MainController.java.
References controller.SimulationChart.updateDisplay(), and controller.Grid.updateGrid().
Referenced by controller.UserInterface.makeBottomPanel().
void controller.MainController.stopSimulation ()
stops the simulation
Definition at line 293 of file MainController.java.
Referenced by controller.MainController.initializeSimulationWithData(), and controller.UserInterface.makeBottomPanel().
void controller.MainController.toggleCellStateForMouseEvent (MouseEvent mouseEvent) private
Clicking empty cell creates a new cell there. Clicking on a cell decreases its state value by 1.
Definition at line 304 of file MainController.java.
References controller.Grid.getPatchAtCoordinate(), and simulationObjects.Patch.toggleCellState().
Referenced by controller.MainController.createGrid().
Member Data Documentation
final int controller.MainController.DEFAULT_HEIGHT = 10 static private
Definition at line 40 of file MainController.java.
Referenced by controller.MainController.setupGridConstraints().
final double controller.MainController.DEFAULT_SPEED = .1 static private
Definition at line 38 of file MainController.java.
final int controller.MainController.DEFAULT_WIDTH = 10 static private
Definition at line 39 of file MainController.java.
Referenced by controller.MainController.setupGridConstraints().
Timeline controller.MainController.myAnimation private
Definition at line 42 of file MainController.java.
SimulationChart controller.MainController.myChart private
Definition at line 45 of file MainController.java.
Grid controller.MainController.myGrid private
Definition at line 43 of file MainController.java.
int controller.MainController.myGridHeight private
Definition at line 48 of file MainController.java.
Referenced by controller.MainController.initializeSimulationObjects().
int controller.MainController.myGridWidth private
Definition at line 46 of file MainController.java.
Referenced by controller.MainController.initializeSimulationObjects().
GridInfo controller.MainController.myInfoSheet = new GridInfo() private
Definition at line 44 of file MainController.java.
UserInterface controller.MainController.myUserInterface private
Definition at line 41 of file MainController.java.
EventHandler<ActionEvent> controller.MainController.oneFrame private
Initial value:
= new EventHandler<ActionEvent>() {
    @Override
    public void handle(ActionEvent evt) {
        stepSimulation();
    }
    }
Function to do each game frame
Definition at line 53 of file MainController.java.
Referenced by controller.MainController.setSimulationSpeed().
ResourceBundle controller.MainController.ourProperties static private
Definition at line 37 of file MainController.java.
Referenced by controller.MainController.main().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/MainController.java