cellsociety_team04: simulationObjects.LifePatch Class Reference
simulationObjects.LifePatch Class Reference
Public Member Functions
LifePatch ()
LifePatch (int x, int y, Grid m)
int countNeighbors ()
void prepareToUpdate ()
void processNeighborsAndUpdateState ()
void toggleCellState ()
void update ()
Public Member Functions inherited from simulationObjects.Patch
Patch ()
Patch (int x, int y, Grid m)
void addCell (Cell cell)
void createBody (int bodyType)
Cell getCell ()
int getGridX ()
int getGridY ()
void getNeighbors ()
int getPreviousState ()
int getState ()
void initialize (int x, int y, Grid m)
boolean isEmpty ()
void prepareToUpdate ()
Patch getRandomEmptyPatch ()
void removeCell ()
void setCellClass (Class<?> c)
void setColorToBody (Color myColor)
void setPreviousState (int myState)
void toggleCellState ()
void update ()
void updateCellConstraints (Cell cell)
Private Attributes
int comfortableAmount = 3
int baselineAmount = 2
Additional Inherited Members
Protected Attributes inherited from simulationObjects.Patch
Cell myCell
int xCoord
int yCoord
Grid grid
List< Patch > myNeighbors
Image image
ImageView myView
State myState
PatchBody myBody
GridInfo infoSheet
Detailed Description
Patch that Simulates GameOfLife
Author
Will Chang
Definition at line 11 of file LifePatch.java.
Constructor & Destructor Documentation
simulationObjects.LifePatch.LifePatch ()
Definition at line 19 of file LifePatch.java.
simulationObjects.LifePatch.LifePatch (int x, int y, Grid m)
Definition at line 23 of file LifePatch.java.
Member Function Documentation
int simulationObjects.LifePatch.countNeighbors ()
Definition at line 28 of file LifePatch.java.
References simulationObjects.Patch.myNeighbors.
Referenced by simulationObjects.LifePatch.processNeighborsAndUpdateState().
void simulationObjects.LifePatch.prepareToUpdate ()
Definition at line 39 of file LifePatch.java.
References simulationObjects.LifePatch.processNeighborsAndUpdateState().
void simulationObjects.LifePatch.processNeighborsAndUpdateState ()
Special rules for Game of Life
Definition at line 46 of file LifePatch.java.
References simulationObjects.LifePatch.countNeighbors(), simulationObjects.Patch.State.EMPTYING, simulationObjects.Patch.State.GENERATING, simulationObjects.Patch.isEmpty(), and simulationObjects.Patch.myState.
Referenced by simulationObjects.LifePatch.prepareToUpdate().
void simulationObjects.LifePatch.toggleCellState ()
Definition at line 58 of file LifePatch.java.
References simulationObjects.Patch.addCell(), simulationObjects.Patch.myState, simulationObjects.Patch.State.OCCUPIED, simulationObjects.Patch.removeCell(), simulationObjects.Patch.xCoord, and simulationObjects.Patch.yCoord.
void simulationObjects.LifePatch.update ()
Definition at line 76 of file LifePatch.java.
References simulationObjects.Patch.addCell(), simulationObjects.Patch.myState, simulationObjects.Patch.State.OCCUPIED, simulationObjects.Patch.removeCell(), simulationObjects.Patch.xCoord, and simulationObjects.Patch.yCoord.
Member Data Documentation
int simulationObjects.LifePatch.baselineAmount = 2 private
Definition at line 17 of file LifePatch.java.
int simulationObjects.LifePatch.comfortableAmount = 3 private
Definition at line 16 of file LifePatch.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/LifePatch.java