cellsociety_team04: simulationObjects.PredatorCell Class Reference
simulationObjects.PredatorCell Class Reference
Classes
enum Phase
Public Member Functions
PredatorCell ()
PredatorCell (int x, int y, int state)
Patch chooseMove (List< Patch > neighbors)
void feed (Patch destination)
ArrayList< Color > getInitialColors ()
int getNextState ()
int getState ()
ArrayList< String > getStateTypes ()
void initialize (int x, int y, int state)
void leaveEgg (Patch current)
void makeMove (Patch current, Patch destination)
void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
List< Patch > processPossibleDestinations (List< Patch > allNeighbors)
void setState (int state)
void update (Patch current, List< Patch > neighbors)
void updateStatesandMakeMoves (Patch current, Patch destination)
Public Member Functions inherited from simulationObjects.Cell
Cell ()
void initialize (int x, int y, int state)
abstract int getState ()
abstract void setState (int state)
abstract void update (Patch currentPatch, List< Patch > neighbors)
abstract void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
abstract int getNextState ()
int getGridX ()
int getGridY ()
void setX (int x)
void setY (int y)
abstract List< String > getStateTypes ()
abstract List< Color > getInitialColors ()
Protected Attributes
int vitality
int timeToBreed
int sharkVitality
int fishVitality
int gestationPeriod
List< Patch > myNeighbors
Protected Attributes inherited from simulationObjects.Cell
GridInfo infoSheet = new GridInfo()
int myX
int myY
int myState
Patch myPatch
List< Integer > myParamList
Private Member Functions
void initializeParameters ()
Private Attributes
final int FISH = 1
final int SHARK = 2
final int DYING = 0
Phase myPhase
Detailed Description
Cell for Predator/Prey simulation
Author
Will Chang
Definition at line 13 of file PredatorCell.java.
Constructor & Destructor Documentation
simulationObjects.PredatorCell.PredatorCell ()
Definition at line 34 of file PredatorCell.java.
References simulationObjects.PredatorCell.initializeParameters().
Referenced by simulationObjects.PredatorCell.leaveEgg().
simulationObjects.PredatorCell.PredatorCell (int x, int y, int state)
Constructor
Parameters
x
y
state
Definition at line 48 of file PredatorCell.java.
References simulationObjects.PredatorCell.fishVitality, controller.GridInfo.getColor(), simulationObjects.Cell.infoSheet, simulationObjects.PredatorCell.initializeParameters(), simulationObjects.Cell.myState, simulationObjects.Cell.myX, simulationObjects.Cell.myY, and simulationObjects.PredatorCell.sharkVitality.
Member Function Documentation
Patch simulationObjects.PredatorCell.chooseMove (List< Patch > neighbors)
Finds possible patches to move and returns a destination. If can't move returns null
Parameters
neighbors
Returns
Patch to move to (contains fish or empty patch) Null if nowhere to move.
Definition at line 71 of file PredatorCell.java.
References simulationObjects.PredatorCell.processPossibleDestinations().
Referenced by simulationObjects.PredatorCell.update().
void simulationObjects.PredatorCell.feed (Patch destination)
Eats another fish
Parameters
destination
Definition at line 85 of file PredatorCell.java.
References simulationObjects.Patch.removeCell().
Referenced by simulationObjects.PredatorCell.updateStatesandMakeMoves().
ArrayList<Color> simulationObjects.PredatorCell.getInitialColors ()
Definition at line 91 of file PredatorCell.java.
int simulationObjects.PredatorCell.getNextState ()
Definition at line 100 of file PredatorCell.java.
References simulationObjects.Cell.myState, and simulationObjects.PredatorCell.SHARK.
int simulationObjects.PredatorCell.getState ()
Definition at line 105 of file PredatorCell.java.
References simulationObjects.Cell.myState.
ArrayList<String> simulationObjects.PredatorCell.getStateTypes ()
Definition at line 110 of file PredatorCell.java.
void simulationObjects.PredatorCell.initialize (int x, int y, int state)
Special constructor for XML
Definition at line 122 of file PredatorCell.java.
References simulationObjects.PredatorCell.initializeParameters(), and simulationObjects.PredatorCell.Phase.STASIS.
void simulationObjects.PredatorCell.initializeParameters () private
Definition at line 250 of file PredatorCell.java.
References simulationObjects.Cell.myParamList.
Referenced by simulationObjects.PredatorCell.initialize(), and simulationObjects.PredatorCell.PredatorCell().
void simulationObjects.PredatorCell.leaveEgg (Patch current)
Breeds
Parameters
current leaves new PredatorCell on old location
Definition at line 134 of file PredatorCell.java.
References simulationObjects.Patch.addCell(), simulationObjects.PredatorCell.FISH, simulationObjects.Patch.getGridX(), simulationObjects.Patch.getGridY(), simulationObjects.Cell.myState, simulationObjects.PredatorCell.PredatorCell(), and simulationObjects.PredatorCell.SHARK.
Referenced by simulationObjects.PredatorCell.updateStatesandMakeMoves().
void simulationObjects.PredatorCell.makeMove (Patch current, Patch destination)
Makes the move
Parameters
current patch
destination patch
Definition at line 153 of file PredatorCell.java.
References simulationObjects.Patch.addCell(), and simulationObjects.Patch.removeCell().
Referenced by simulationObjects.PredatorCell.updateStatesandMakeMoves().
void simulationObjects.PredatorCell.prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
Sets state for updating
Definition at line 162 of file PredatorCell.java.
References simulationObjects.Cell.myPatch, and simulationObjects.PredatorCell.Phase.UPDATING.
List<Patch> simulationObjects.PredatorCell.processPossibleDestinations (List< Patch > allNeighbors)
Processes locations to move to
Parameters
allNeighbors it can move to
Returns
list of Patches to move to
Definition at line 174 of file PredatorCell.java.
References simulationObjects.PredatorCell.FISH, simulationObjects.Cell.getState(), and simulationObjects.Cell.myState.
Referenced by simulationObjects.PredatorCell.chooseMove().
void simulationObjects.PredatorCell.setState (int state)
Definition at line 195 of file PredatorCell.java.
References controller.GridInfo.getColor(), simulationObjects.Cell.infoSheet, and simulationObjects.Cell.myState.
Referenced by simulationObjects.PredatorCell.update().
void simulationObjects.PredatorCell.update (Patch current, List< Patch > neighbors)
Updates the Predator Cell
returns the current location if the Predator Cell is still alive returns null if the shark cell's vitality = 0
Definition at line 211 of file PredatorCell.java.
References simulationObjects.PredatorCell.chooseMove(), simulationObjects.PredatorCell.setState(), simulationObjects.PredatorCell.Phase.STASIS, simulationObjects.PredatorCell.updateStatesandMakeMoves(), and simulationObjects.PredatorCell.Phase.UPDATING.
void simulationObjects.PredatorCell.updateStatesandMakeMoves (Patch current, Patch destination)
Updates the state and moves based on Shark vs Fish
Parameters
current patch
destination patch
Definition at line 231 of file PredatorCell.java.
References simulationObjects.PredatorCell.feed(), simulationObjects.PredatorCell.gestationPeriod, simulationObjects.Patch.isEmpty(), simulationObjects.PredatorCell.leaveEgg(), simulationObjects.PredatorCell.makeMove(), and simulationObjects.Cell.myState.
Referenced by simulationObjects.PredatorCell.update().
Member Data Documentation
final int simulationObjects.PredatorCell.DYING = 0 private
Definition at line 21 of file PredatorCell.java.
final int simulationObjects.PredatorCell.FISH = 1 private
Definition at line 19 of file PredatorCell.java.
Referenced by simulationObjects.PredatorCell.leaveEgg(), and simulationObjects.PredatorCell.processPossibleDestinations().
int simulationObjects.PredatorCell.fishVitality protected
Definition at line 26 of file PredatorCell.java.
Referenced by simulationObjects.PredatorCell.PredatorCell().
int simulationObjects.PredatorCell.gestationPeriod protected
Definition at line 27 of file PredatorCell.java.
Referenced by simulationObjects.PredatorCell.updateStatesandMakeMoves().
List<Patch> simulationObjects.PredatorCell.myNeighbors protected
Definition at line 32 of file PredatorCell.java.
Phase simulationObjects.PredatorCell.myPhase private
Definition at line 30 of file PredatorCell.java.
final int simulationObjects.PredatorCell.SHARK = 2 private
Definition at line 20 of file PredatorCell.java.
Referenced by simulationObjects.PredatorCell.getNextState(), and simulationObjects.PredatorCell.leaveEgg().
int simulationObjects.PredatorCell.sharkVitality protected
Definition at line 25 of file PredatorCell.java.
Referenced by simulationObjects.PredatorCell.PredatorCell().
int simulationObjects.PredatorCell.timeToBreed protected
Definition at line 24 of file PredatorCell.java.
int simulationObjects.PredatorCell.vitality protected
Definition at line 23 of file PredatorCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/PredatorCell.java