cellsociety_team04: simulationObjects.SugarCell Class Reference
simulationObjects.SugarCell Class Reference
Classes
enum Phase
Public Member Functions
SugarCell ()
SugarCell (int x, int y, int state)
List< Color > getInitialColors ()
int getNextState ()
int getState ()
List< String > getStateTypes ()
void initialize (int x, int y, int state)
void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
void setState (int state)
void update (Patch current, List< Patch > neighbors)
Public Member Functions inherited from simulationObjects.Cell
Cell ()
void initialize (int x, int y, int state)
abstract int getState ()
abstract void setState (int state)
abstract void update (Patch currentPatch, List< Patch > neighbors)
abstract void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
abstract int getNextState ()
int getGridX ()
int getGridY ()
void setX (int x)
void setY (int y)
abstract List< String > getStateTypes ()
abstract List< Color > getInitialColors ()
Protected Attributes
int currentSugar = 25
int sugarMetabolism = 4
List< Patch > myNeighbors
Protected Attributes inherited from simulationObjects.Cell
GridInfo infoSheet = new GridInfo()
int myX
int myY
int myState
Patch myPatch
List< Integer > myParamList
Private Member Functions
Patch chooseMove (List< Patch > neighbors)
void makeMove (Patch currentPatch, Patch destination)
Patch pickClosestMove (List< Patch > destinations)
List< Patch > processPossibleDestinations (List< Patch > neighbors)
void updateStatesandMakeMoves (Patch current, Patch destination)
Private Attributes
final int OCCUPIED = 1
final int DYING = 0
Phase myPhase
Detailed Description
Definition at line 8 of file SugarCell.java.
Constructor & Destructor Documentation
simulationObjects.SugarCell.SugarCell ()
Definition at line 23 of file SugarCell.java.
simulationObjects.SugarCell.SugarCell (int x, int y, int state)
Definition at line 28 of file SugarCell.java.
References controller.GridInfo.getColor(), simulationObjects.Cell.infoSheet, simulationObjects.Cell.myState, simulationObjects.Cell.myX, and simulationObjects.Cell.myY.
Member Function Documentation
Patch simulationObjects.SugarCell.chooseMove (List< Patch > neighbors) private
Definition at line 39 of file SugarCell.java.
References simulationObjects.SugarCell.pickClosestMove(), and simulationObjects.SugarCell.processPossibleDestinations().
Referenced by simulationObjects.SugarCell.update().
List<Color> simulationObjects.SugarCell.getInitialColors ()
Definition at line 50 of file SugarCell.java.
int simulationObjects.SugarCell.getNextState ()
Definition at line 62 of file SugarCell.java.
References simulationObjects.Cell.myState, and simulationObjects.SugarCell.OCCUPIED.
int simulationObjects.SugarCell.getState ()
Definition at line 67 of file SugarCell.java.
References simulationObjects.Cell.myState.
List<String> simulationObjects.SugarCell.getStateTypes ()
Definition at line 72 of file SugarCell.java.
void simulationObjects.SugarCell.initialize (int x, int y, int state)
Definition at line 84 of file SugarCell.java.
References simulationObjects.SugarCell.Phase.STASIS.
void simulationObjects.SugarCell.makeMove (Patch currentPatch, Patch destination) private
Definition at line 89 of file SugarCell.java.
References simulationObjects.Patch.addCell(), and simulationObjects.Patch.removeCell().
Referenced by simulationObjects.SugarCell.updateStatesandMakeMoves().
Patch simulationObjects.SugarCell.pickClosestMove (List< Patch > destinations) private
Definition at line 94 of file SugarCell.java.
References simulationObjects.Cell.myX, and simulationObjects.Cell.myY.
Referenced by simulationObjects.SugarCell.chooseMove().
void simulationObjects.SugarCell.prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
Definition at line 111 of file SugarCell.java.
References simulationObjects.Cell.myPatch, and simulationObjects.SugarCell.Phase.UPDATING.
List<Patch> simulationObjects.SugarCell.processPossibleDestinations (List< Patch > neighbors) private
Definition at line 116 of file SugarCell.java.
Referenced by simulationObjects.SugarCell.chooseMove().
void simulationObjects.SugarCell.setState (int state)
Definition at line 139 of file SugarCell.java.
References controller.GridInfo.getColor(), simulationObjects.Cell.infoSheet, and simulationObjects.Cell.myState.
Referenced by simulationObjects.SugarCell.update().
void simulationObjects.SugarCell.update (Patch current, List< Patch > neighbors)
Definition at line 147 of file SugarCell.java.
References simulationObjects.SugarCell.chooseMove(), simulationObjects.Cell.myState, simulationObjects.SugarCell.setState(), simulationObjects.SugarCell.Phase.STASIS, simulationObjects.SugarCell.updateStatesandMakeMoves(), and simulationObjects.SugarCell.Phase.UPDATING.
void simulationObjects.SugarCell.updateStatesandMakeMoves (Patch current, Patch destination) private
Definition at line 161 of file SugarCell.java.
References simulationObjects.SugarCell.makeMove(), simulationObjects.Cell.myState, and simulationObjects.SugarCell.sugarMetabolism.
Referenced by simulationObjects.SugarCell.update().
Member Data Documentation
int simulationObjects.SugarCell.currentSugar = 25 protected
Definition at line 14 of file SugarCell.java.
final int simulationObjects.SugarCell.DYING = 0 private
Definition at line 19 of file SugarCell.java.
List<Patch> simulationObjects.SugarCell.myNeighbors protected
Definition at line 16 of file SugarCell.java.
Phase simulationObjects.SugarCell.myPhase private
Definition at line 21 of file SugarCell.java.
final int simulationObjects.SugarCell.OCCUPIED = 1 private
Definition at line 17 of file SugarCell.java.
Referenced by simulationObjects.SugarCell.getNextState().
int simulationObjects.SugarCell.sugarMetabolism = 4 protected
Definition at line 15 of file SugarCell.java.
Referenced by simulationObjects.SugarCell.updateStatesandMakeMoves().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/SugarCell.java