cellsociety_team04: simulationObjects.SugarPatch Class Reference
simulationObjects.SugarPatch Class Reference
Public Member Functions
SugarPatch ()
SugarPatch (int x, int y, Grid m)
void createBody (int bodyType)
int getCurrentSugar ()
void getNeighbors ()
void getNeighbors (int vision)
void initialize (int x, int y, Grid m)
void removeSugar ()
void setColorToBody ()
void sugarGrowBack ()
void update ()
Public Member Functions inherited from simulationObjects.Patch
Patch ()
Patch (int x, int y, Grid m)
void addCell (Cell cell)
void createBody (int bodyType)
Cell getCell ()
int getGridX ()
int getGridY ()
void getNeighbors ()
int getPreviousState ()
int getState ()
void initialize (int x, int y, Grid m)
boolean isEmpty ()
void prepareToUpdate ()
Patch getRandomEmptyPatch ()
void removeCell ()
void setCellClass (Class<?> c)
void setColorToBody (Color myColor)
void setPreviousState (int myState)
void toggleCellState ()
void update ()
void updateCellConstraints (Cell cell)
Protected Attributes
int vision = 1
int colorGradient = 4
int sugarGrowBackRate = 1
Protected Attributes inherited from simulationObjects.Patch
Cell myCell
int xCoord
int yCoord
Grid grid
List< Patch > myNeighbors
Image image
ImageView myView
State myState
PatchBody myBody
GridInfo infoSheet
Private Attributes
int currentSugar = 0
Detailed Description
Definition at line 5 of file SugarPatch.java.
Constructor & Destructor Documentation
simulationObjects.SugarPatch.SugarPatch ()
Definition at line 11 of file SugarPatch.java.
simulationObjects.SugarPatch.SugarPatch (int x, int y, Grid m)
Definition at line 15 of file SugarPatch.java.
Member Function Documentation
void simulationObjects.SugarPatch.createBody (int bodyType)
creates a patch body for the patch
Parameters
bodyType what kind of shape it is
Definition at line 26 of file SugarPatch.java.
References controller.Grid.getGridHeight(), controller.Grid.getGridWidth(), simulationObjects.Patch.grid, simulationObjects.Patch.myBody, simulationObjects.Patch.myCell, simulationObjects.Patch.updateCellConstraints(), simulationObjects.Patch.xCoord, and simulationObjects.Patch.yCoord.
int simulationObjects.SugarPatch.getCurrentSugar ()
Definition at line 55 of file SugarPatch.java.
References simulationObjects.SugarPatch.currentSugar.
void simulationObjects.SugarPatch.getNeighbors ()
Definition at line 60 of file SugarPatch.java.
void simulationObjects.SugarPatch.getNeighbors (int vision)
Definition at line 64 of file SugarPatch.java.
References controller.Grid.getNeighborsAround(), simulationObjects.Patch.grid, simulationObjects.Patch.myNeighbors, simulationObjects.Patch.xCoord, and simulationObjects.Patch.yCoord.
void simulationObjects.SugarPatch.initialize (int x, int y, Grid m)
Definition at line 71 of file SugarPatch.java.
void simulationObjects.SugarPatch.removeSugar ()
Definition at line 77 of file SugarPatch.java.
void simulationObjects.SugarPatch.setColorToBody ()
Definition at line 81 of file SugarPatch.java.
References controller.GridInfo.getColor(), simulationObjects.Patch.infoSheet, and simulationObjects.Patch.myBody.
Referenced by simulationObjects.SugarPatch.update().
void simulationObjects.SugarPatch.sugarGrowBack ()
Definition at line 90 of file SugarPatch.java.
References simulationObjects.SugarPatch.sugarGrowBackRate.
Referenced by simulationObjects.SugarPatch.update().
void simulationObjects.SugarPatch.update ()
Definition at line 96 of file SugarPatch.java.
References simulationObjects.Cell.getState(), simulationObjects.Patch.myCell, simulationObjects.Patch.myNeighbors, simulationObjects.Patch.removeCell(), simulationObjects.SugarPatch.setColorToBody(), simulationObjects.SugarPatch.sugarGrowBack(), and simulationObjects.Cell.update().
Member Data Documentation
int simulationObjects.SugarPatch.colorGradient = 4 protected
Definition at line 8 of file SugarPatch.java.
int simulationObjects.SugarPatch.currentSugar = 0 private
Definition at line 6 of file SugarPatch.java.
Referenced by simulationObjects.SugarPatch.getCurrentSugar().
int simulationObjects.SugarPatch.sugarGrowBackRate = 1 protected
Definition at line 9 of file SugarPatch.java.
Referenced by simulationObjects.SugarPatch.sugarGrowBack().
int simulationObjects.SugarPatch.vision = 1 protected
Definition at line 7 of file SugarPatch.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/SugarPatch.java