cellsociety_team04: simulationObjects.ForestCell Class Reference
simulationObjects.ForestCell Class Reference
Public Member Functions
ForestCell ()
void catchFire (Patch currentPatch)
ArrayList< Color > getInitialColors ()
int getNextState ()
int getState ()
ArrayList< String > getStateTypes ()
void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
void setState (int state)
void update (Patch currentPatch, List< Patch > neighbors)
boolean willCatchFire (List< Patch > neighbors)
Public Member Functions inherited from simulationObjects.Cell
Cell ()
void initialize (int x, int y, int state)
abstract int getState ()
abstract void setState (int state)
abstract void update (Patch currentPatch, List< Patch > neighbors)
abstract void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
abstract int getNextState ()
int getGridX ()
int getGridY ()
void setX (int x)
void setY (int y)
abstract List< String > getStateTypes ()
abstract List< Color > getInitialColors ()
Private Member Functions
void burnDown (Patch currentPatch)
Private Attributes
final int EMPTY = 0
final int ONFIRE = 1
final int TREE = 2
Additional Inherited Members
Protected Attributes inherited from simulationObjects.Cell
GridInfo infoSheet = new GridInfo()
int myX
int myY
int myState
Patch myPatch
List< Integer > myParamList
Detailed Description
Definition at line 8 of file ForestCell.java.
Constructor & Destructor Documentation
simulationObjects.ForestCell.ForestCell ()
Definition at line 14 of file ForestCell.java.
Member Function Documentation
void simulationObjects.ForestCell.burnDown (Patch currentPatch) private
Definition at line 18 of file ForestCell.java.
References simulationObjects.ForestCell.setState().
Referenced by simulationObjects.ForestCell.update().
void simulationObjects.ForestCell.catchFire (Patch currentPatch)
Definition at line 22 of file ForestCell.java.
References simulationObjects.ForestCell.setState().
Referenced by simulationObjects.ForestCell.update().
ArrayList<Color> simulationObjects.ForestCell.getInitialColors ()
Definition at line 27 of file ForestCell.java.
int simulationObjects.ForestCell.getNextState ()
Definition at line 36 of file ForestCell.java.
References simulationObjects.Cell.myState.
int simulationObjects.ForestCell.getState ()
Definition at line 41 of file ForestCell.java.
References simulationObjects.Cell.myState.
ArrayList<String> simulationObjects.ForestCell.getStateTypes ()
Definition at line 46 of file ForestCell.java.
void simulationObjects.ForestCell.prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
Definition at line 55 of file ForestCell.java.
References simulationObjects.Cell.myState, and simulationObjects.Patch.setPreviousState().
void simulationObjects.ForestCell.setState (int state)
Definition at line 60 of file ForestCell.java.
References controller.GridInfo.getColor(), simulationObjects.Cell.infoSheet, and simulationObjects.Cell.myState.
Referenced by simulationObjects.ForestCell.burnDown(), simulationObjects.ForestCell.catchFire(), and simulationObjects.ForestCell.update().
void simulationObjects.ForestCell.update (Patch currentPatch, List< Patch > neighbors)
Definition at line 70 of file ForestCell.java.
References simulationObjects.ForestCell.burnDown(), simulationObjects.ForestCell.catchFire(), simulationObjects.Cell.myState, simulationObjects.ForestCell.setState(), and simulationObjects.ForestCell.willCatchFire().
boolean simulationObjects.ForestCell.willCatchFire (List< Patch > neighbors)
Definition at line 87 of file ForestCell.java.
References controller.GridInfo.getParam(), simulationObjects.Cell.infoSheet, and simulationObjects.ForestCell.ONFIRE.
Referenced by simulationObjects.ForestCell.update().
Member Data Documentation
final int simulationObjects.ForestCell.EMPTY = 0 private
Definition at line 10 of file ForestCell.java.
final int simulationObjects.ForestCell.ONFIRE = 1 private
Definition at line 11 of file ForestCell.java.
Referenced by simulationObjects.ForestCell.willCatchFire().
final int simulationObjects.ForestCell.TREE = 2 private
Definition at line 12 of file ForestCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/ForestCell.java