cellsociety_team04: simulationObjects.Cell Class Reference
simulationObjects.Cell Class Reference abstract
Classes
enum relativePosition
Public Member Functions
Cell ()
void initialize (int x, int y, int state)
abstract int getState ()
abstract void setState (int state)
abstract void update (Patch currentPatch, List< Patch > neighbors)
abstract void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
abstract int getNextState ()
int getGridX ()
int getGridY ()
void setX (int x)
void setY (int y)
abstract List< String > getStateTypes ()
abstract List< Color > getInitialColors ()
Protected Attributes
GridInfo infoSheet = new GridInfo()
int myX
int myY
int myState
Patch myPatch
List< Integer > myParamList
Detailed Description
Parent Class of Cell Hierarchy
Author
Everyone
Definition at line 15 of file Cell.java.
Constructor & Destructor Documentation
simulationObjects.Cell.Cell ()
Definition at line 25 of file Cell.java.
References controller.GridInfo.getParamList().
Member Function Documentation
int simulationObjects.Cell.getGridX ()
Returns the x location in the grid
Returns
myX
Definition at line 89 of file Cell.java.
References simulationObjects.Cell.myX.
int simulationObjects.Cell.getGridY ()
Returns the y location in the grid
Returns
myY
Definition at line 97 of file Cell.java.
References simulationObjects.Cell.myY.
abstract List<Color> simulationObjects.Cell.getInitialColors () abstract
Gets the initial colors of the cell
Returns
Referenced by controller.Parser.setCellStates().
abstract int simulationObjects.Cell.getNextState () abstract
Gets the next state of the Cell
Returns
Referenced by simulationObjects.Patch.toggleCellState().
abstract int simulationObjects.Cell.getState () abstract
Returns the state of the cell.
Returns
state of the cell
Referenced by controller.Grid.countCellInPatch(), simulationObjects.PredatorCell.processPossibleDestinations(), simulationObjects.SugarPatch.update(), and simulationObjects.Patch.update().
abstract List<String> simulationObjects.Cell.getStateTypes () abstract
Gets the different states of the cell
Returns
Referenced by controller.Parser.setCellStates().
void simulationObjects.Cell.initialize (int x, int y, int state)
Special constructor for XML reads
Parameters
x
y
state
Definition at line 36 of file Cell.java.
References simulationObjects.Cell.setState(), simulationObjects.Cell.setX(), and simulationObjects.Cell.setY().
abstract void simulationObjects.Cell.prepareToUpdate (Patch currentPatch, List< Patch > neighbors) abstract
Prepares the cell for updating
Parameters
currentPatch
neighbors
Referenced by simulationObjects.Patch.prepareToUpdate().
abstract void simulationObjects.Cell.setState (int state) abstract
Sets the state of the cell
Parameters
state of the cell
Referenced by controller.MainController.createCell(), simulationObjects.Patch.createNewCell(), simulationObjects.Cell.initialize(), simulationObjects.SegCell.isSatisfied(), and simulationObjects.Patch.toggleCellState().
void simulationObjects.Cell.setX (int x)
Sets x location
Parameters
x
Definition at line 105 of file Cell.java.
Referenced by controller.MainController.createCell(), simulationObjects.Patch.createNewCell(), and simulationObjects.Cell.initialize().
void simulationObjects.Cell.setY (int y)
Sets y location
Parameters
y
Definition at line 113 of file Cell.java.
Referenced by controller.MainController.createCell(), simulationObjects.Patch.createNewCell(), and simulationObjects.Cell.initialize().
abstract void simulationObjects.Cell.update (Patch currentPatch, List< Patch > neighbors) abstract
Updates the cell, applies the rules of the simulation
Parameters
currentPatch the cell is on
neighbors patches around the cell's currentPatch
Referenced by simulationObjects.SugarPatch.update(), and simulationObjects.Patch.update().
Member Data Documentation
GridInfo simulationObjects.Cell.infoSheet = new GridInfo() protected
Definition at line 17 of file Cell.java.
Referenced by simulationObjects.SegCell.isSatisfied(), simulationObjects.LifeCell.LifeCell(), simulationObjects.PredatorCell.PredatorCell(), simulationObjects.ForestCell.setState(), simulationObjects.SegCell.setState(), simulationObjects.SugarCell.setState(), simulationObjects.PredatorCell.setState(), simulationObjects.SugarCell.SugarCell(), and simulationObjects.ForestCell.willCatchFire().
List<Integer> simulationObjects.Cell.myParamList protected
Definition at line 23 of file Cell.java.
Referenced by simulationObjects.PredatorCell.initializeParameters().
Patch simulationObjects.Cell.myPatch protected
Definition at line 22 of file Cell.java.
Referenced by simulationObjects.SugarCell.prepareToUpdate(), simulationObjects.AntCell.prepareToUpdate(), simulationObjects.PredatorCell.prepareToUpdate(), and simulationObjects.AntCell.returnToNest().
int simulationObjects.Cell.myState protected
Definition at line 21 of file Cell.java.
Referenced by simulationObjects.SegCell.getNextState(), simulationObjects.ForestCell.getNextState(), simulationObjects.SugarCell.getNextState(), simulationObjects.PredatorCell.getNextState(), simulationObjects.LifeCell.getState(), simulationObjects.ForestCell.getState(), simulationObjects.SegCell.getState(), simulationObjects.SugarCell.getState(), simulationObjects.PredatorCell.getState(), simulationObjects.SegCell.isSatisfied(), simulationObjects.PredatorCell.leaveEgg(), simulationObjects.LifeCell.LifeCell(), simulationObjects.PredatorCell.PredatorCell(), simulationObjects.ForestCell.prepareToUpdate(), simulationObjects.PredatorCell.processPossibleDestinations(), simulationObjects.LifeCell.setState(), simulationObjects.ForestCell.setState(), simulationObjects.SegCell.setState(), simulationObjects.SugarCell.setState(), simulationObjects.PredatorCell.setState(), simulationObjects.SugarCell.SugarCell(), simulationObjects.ForestCell.update(), simulationObjects.SugarCell.update(), simulationObjects.SugarCell.updateStatesandMakeMoves(), and simulationObjects.PredatorCell.updateStatesandMakeMoves().
int simulationObjects.Cell.myX protected
Definition at line 19 of file Cell.java.
Referenced by simulationObjects.Cell.getGridX(), simulationObjects.LifeCell.LifeCell(), simulationObjects.SugarCell.pickClosestMove(), simulationObjects.PredatorCell.PredatorCell(), and simulationObjects.SugarCell.SugarCell().
int simulationObjects.Cell.myY protected
Definition at line 20 of file Cell.java.
Referenced by simulationObjects.Cell.getGridY(), simulationObjects.LifeCell.LifeCell(), simulationObjects.SugarCell.pickClosestMove(), simulationObjects.PredatorCell.PredatorCell(), and simulationObjects.SugarCell.SugarCell().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/Cell.java