cellsociety_team04: simulationObjects.PatchBodyHexagon Class Reference
simulationObjects.PatchBodyHexagon Class Reference
Public Member Functions
PatchBodyHexagon (int x, int y, double gridPixelHeight, double gridPixelWidth, int gridHeight, int gridWidth)
void buildBody ()
Public Member Functions inherited from simulationObjects.PatchBody
PatchBody (int x, int y)
abstract void buildBody ()
void createPolyFromPoints (Double[] pts)
Point getCenter ()
int getPatchHeight ()
int getPatchWidth ()
void setCenter (Point c)
void setPatchHeight (int h)
void setPatchWidth (int w)
Private Attributes
double mySideLength
Additional Inherited Members
Public Attributes inherited from simulationObjects.PatchBody
int myX
int myY
Protected Attributes inherited from simulationObjects.PatchBody
GridInfo infoSheet = new GridInfo()
Detailed Description
hexagon implementation of patch body
Author
Davis
Definition at line 12 of file PatchBodyHexagon.java.
Constructor & Destructor Documentation
simulationObjects.PatchBodyHexagon.PatchBodyHexagon (int x, int y, double gridPixelHeight, double gridPixelWidth, int gridHeight, int gridWidth)
Definition at line 16 of file PatchBodyHexagon.java.
References simulationObjects.PatchBodyHexagon.buildBody(), simulationObjects.PatchBody.getPatchWidth(), simulationObjects.PatchBody.setPatchHeight(), and simulationObjects.PatchBody.setPatchWidth().
Member Function Documentation
void simulationObjects.PatchBodyHexagon.buildBody ()
Definition at line 26 of file PatchBodyHexagon.java.
References simulationObjects.PatchBody.createPolyFromPoints(), simulationObjects.PatchBody.getPatchHeight(), simulationObjects.PatchBodyHexagon.mySideLength, simulationObjects.PatchBody.myX, simulationObjects.PatchBody.myY, and simulationObjects.PatchBody.setCenter().
Referenced by simulationObjects.PatchBodyHexagon.PatchBodyHexagon().
Member Data Documentation
double simulationObjects.PatchBodyHexagon.mySideLength private
Definition at line 14 of file PatchBodyHexagon.java.
Referenced by simulationObjects.PatchBodyHexagon.buildBody().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/PatchBodyHexagon.java