cellsociety_team04: controller.Grid Class Reference
controller.Grid Class Reference
Public Member Functions
Grid (int width, int height)
void initializeCellCounts ()
void updateGrid ()
HashMap< Integer, Integer > getCellCounts ()
void addPatchAtPoint (Patch patch)
void removeCellinPatch (int xCoord, int yCoord)
List< Patch > getNeighborsAround (int xCoord, int yCoord)
Patch getPatchAtPoint (int i, int j)
Patch getPatchAtCoordinate (int i, int j)
int getGridWidth ()
int getGridHeight ()
Patch findEmptyPatch ()
void updateAllNeighborhoods ()
void changeRulesTo (GridEdgeRules rules)
void updateBackgroundColor (Color myColor)
int getTotalCells ()
void setPatchBody (int i)
Private Member Functions
void updateAllPatches ()
void prepareToUpdateAllPatches ()
void countCellInPatch (Patch p)
void resetCellCounts ()
void addPatchToGrid (Patch patch, int gridX, int gridY)
Private Attributes
Patch[][] gridArray
int[] xDelta = { -1, 1, 0, 0, 1, 1, -1, -1 }
int[] yDelta = { 0, 0, 1, -1, 1, -1, 1, -1 }
int gWidth
int gHeight
GridInfo infoSheet
HashMap< Integer, Integer > cellCounts
int totalCells
GridEdgeRules myEdgeRules
List< Patch > emptyPatches
Detailed Description
Manages grid properties and contents
Author
Will Chang
Definition at line 19 of file Grid.java.
Constructor & Destructor Documentation
controller.Grid.Grid (int width, int height)
Constructs the Grid, initiates private variables
Parameters
width of the grid
height of the grid
rules Edge rules for the grid
Definition at line 42 of file Grid.java.
Member Function Documentation
void controller.Grid.addPatchAtPoint (Patch patch)
Adds patch in specific location in the Grid
Parameters
patch to be added
xCoord in grid
yCoord in grid
Definition at line 118 of file Grid.java.
References controller.Grid.addPatchToGrid(), simulationObjects.Patch.getGridX(), and simulationObjects.Patch.getGridY().
Referenced by controller.MainController.initializeSimulationObjects().
void controller.Grid.addPatchToGrid (Patch patch, int gridX, int gridY) private
Definition at line 123 of file Grid.java.
References simulationObjects.Patch.createBody().
Referenced by controller.Grid.addPatchAtPoint().
void controller.Grid.changeRulesTo (GridEdgeRules rules)
Change current grid's edge rules to new rules
Parameters
rules
Definition at line 243 of file Grid.java.
References controller.Grid.updateAllNeighborhoods().
Referenced by controller.UserInterface.makeBottomPanel().
void controller.Grid.countCellInPatch (Patch p) private
Definition at line 86 of file Grid.java.
References simulationObjects.Patch.getCell(), simulationObjects.Cell.getState(), and simulationObjects.Patch.isEmpty().
Referenced by controller.Grid.updateAllPatches().
Patch controller.Grid.findEmptyPatch ()
Finds empty Patch
Returns
an empty Patch
Definition at line 208 of file Grid.java.
Referenced by simulationObjects.Patch.getRandomEmptyPatch().
HashMap<Integer, Integer> controller.Grid.getCellCounts ()
Definition at line 103 of file Grid.java.
References controller.Grid.cellCounts.
Referenced by controller.SimulationChart.plotData().
int controller.Grid.getGridHeight ()
Get the grid's height
Returns
gHeight
Definition at line 199 of file Grid.java.
References controller.Grid.gHeight.
Referenced by simulationObjects.SugarPatch.createBody(), simulationObjects.Patch.createBody(), controller.UserInterface.makeBottomPanel(), and controller.SimulationChart.SimulationChart().
int controller.Grid.getGridWidth ()
Get the grid's width
Returns
gWidth
Definition at line 190 of file Grid.java.
References controller.Grid.gWidth.
Referenced by simulationObjects.SugarPatch.createBody(), simulationObjects.Patch.createBody(), controller.UserInterface.makeBottomPanel(), and controller.SimulationChart.SimulationChart().
List<Patch> controller.Grid.getNeighborsAround (int xCoord, int yCoord)
Retrieves all neighboring patches around a point
Parameters
xCoord
yCoord
Returns
Definition at line 147 of file Grid.java.
References controller.GridEdgeRules.applyRulesAndGetNeighbors(), and controller.GridInfo.getAdjacentType().
Referenced by simulationObjects.SugarPatch.getNeighbors(), and simulationObjects.Patch.getNeighbors().
Patch controller.Grid.getPatchAtCoordinate (int i, int j)
get patch given a scene coordinate this is with respect to the scene (pixels), NOT to the grid
Parameters
i the explicit pixel x location
j the explicit pixel y location
Returns
Definition at line 176 of file Grid.java.
Referenced by controller.MainController.toggleCellStateForMouseEvent().
Patch controller.Grid.getPatchAtPoint (int i, int j)
get patch in our grid system
Parameters
i
j
Returns
Definition at line 164 of file Grid.java.
Referenced by controller.DefaultEdgeRules.applyRulesAndGetNeighbors(), and controller.ToroidalEdgeRules.applyRulesAndGetNeighbors().
int controller.Grid.getTotalCells ()
Return the total number of cells in the simulation.
Returns
Definition at line 267 of file Grid.java.
References controller.Grid.totalCells.
void controller.Grid.initializeCellCounts ()
Definition at line 52 of file Grid.java.
References controller.GridInfo.getMaxCellState().
Referenced by controller.MainController.initializeSimulationObjects().
void controller.Grid.prepareToUpdateAllPatches () private
Definition at line 78 of file Grid.java.
Referenced by controller.Grid.updateGrid().
void controller.Grid.removeCellinPatch (int xCoord, int yCoord)
Remove cell from specific location in the Grid
Parameters
xCoord in grid
yCoord in grid
Definition at line 136 of file Grid.java.
References simulationObjects.Patch.removeCell().
void controller.Grid.resetCellCounts () private
Definition at line 95 of file Grid.java.
Referenced by controller.Grid.updateGrid().
void controller.Grid.setPatchBody (int i)
create a patch body for each cell, given the user selection
Parameters
i
Definition at line 278 of file Grid.java.
Referenced by controller.UserInterface.makeBottomPanel().
void controller.Grid.updateAllNeighborhoods ()
Updates the neighborhoods of all patches based on the grid's rules
Definition at line 230 of file Grid.java.
Referenced by controller.Grid.changeRulesTo(), and controller.MainController.initializeSimulationObjects().
void controller.Grid.updateAllPatches () private
Definition at line 69 of file Grid.java.
References controller.Grid.countCellInPatch().
Referenced by controller.Grid.updateGrid().
void controller.Grid.updateBackgroundColor (Color myColor)
Updates the background color.
Parameters
myColor
Definition at line 254 of file Grid.java.
Referenced by controller.ColorPicker.buildColorPickerMenu().
void controller.Grid.updateGrid ()
Makes a step in the simulation, updates everything sequentially
Definition at line 63 of file Grid.java.
References controller.Grid.prepareToUpdateAllPatches(), controller.Grid.resetCellCounts(), and controller.Grid.updateAllPatches().
Referenced by controller.MainController.stepSimulation().
Member Data Documentation
HashMap<Integer, Integer> controller.Grid.cellCounts private
Definition at line 27 of file Grid.java.
Referenced by controller.Grid.getCellCounts().
List<Patch> controller.Grid.emptyPatches private
Definition at line 30 of file Grid.java.
int controller.Grid.gHeight private
Definition at line 25 of file Grid.java.
Referenced by controller.Grid.getGridHeight().
Patch [][] controller.Grid.gridArray private
Definition at line 21 of file Grid.java.
int controller.Grid.gWidth private
Definition at line 24 of file Grid.java.
Referenced by controller.Grid.getGridWidth().
GridInfo controller.Grid.infoSheet private
Definition at line 26 of file Grid.java.
GridEdgeRules controller.Grid.myEdgeRules private
Definition at line 29 of file Grid.java.
int controller.Grid.totalCells private
Definition at line 28 of file Grid.java.
Referenced by controller.Grid.getTotalCells().
int [] controller.Grid.xDelta = { -1, 1, 0, 0, 1, 1, -1, -1 } private
Definition at line 22 of file Grid.java.
int [] controller.Grid.yDelta = { 0, 0, 1, -1, 1, -1, 1, -1 } private
Definition at line 23 of file Grid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/controller/Grid.java