cellsociety_team04: simulationObjects.SegCell Class Reference
simulationObjects.SegCell Class Reference
Public Member Functions
SegCell ()
ArrayList< Color > getInitialColors ()
int getNextState ()
int getState ()
ArrayList< String > getStateTypes ()
void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
void setState (int state)
void update (Patch currentPatch, List< Patch > neighbors)
Public Member Functions inherited from simulationObjects.Cell
Cell ()
void initialize (int x, int y, int state)
abstract int getState ()
abstract void setState (int state)
abstract void update (Patch currentPatch, List< Patch > neighbors)
abstract void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
abstract int getNextState ()
int getGridX ()
int getGridY ()
void setX (int x)
void setY (int y)
abstract List< String > getStateTypes ()
abstract List< Color > getInitialColors ()
Private Member Functions
boolean isSatisfied (Patch currentPatch, List< Patch > neighbors)
Static Private Attributes
static final int STATE_X = 1
static final int STATE_O = 2
Additional Inherited Members
Protected Attributes inherited from simulationObjects.Cell
GridInfo infoSheet = new GridInfo()
int myX
int myY
int myState
Patch myPatch
List< Integer > myParamList
Detailed Description
Cell for the segregation simulation
Author
Davis Gossage
Definition at line 15 of file SegCell.java.
Constructor & Destructor Documentation
simulationObjects.SegCell.SegCell ()
Definition at line 20 of file SegCell.java.
Member Function Documentation
ArrayList<Color> simulationObjects.SegCell.getInitialColors ()
Definition at line 25 of file SegCell.java.
int simulationObjects.SegCell.getNextState ()
Definition at line 34 of file SegCell.java.
References simulationObjects.Cell.myState, and simulationObjects.SegCell.STATE_O.
int simulationObjects.SegCell.getState ()
Definition at line 42 of file SegCell.java.
References simulationObjects.Cell.myState.
ArrayList<String> simulationObjects.SegCell.getStateTypes ()
Definition at line 47 of file SegCell.java.
boolean simulationObjects.SegCell.isSatisfied (Patch currentPatch, List< Patch > neighbors) private
Determines whether the cell is satisfied given its neighbors
Parameters
currentPatch the patch the cell is in
neighbors the neighbors of the cell's patch
Returns
satisfied or not
Definition at line 64 of file SegCell.java.
References simulationObjects.Patch.getCell(), simulationObjects.Cell.infoSheet, simulationObjects.Cell.myState, and simulationObjects.Cell.setState().
Referenced by simulationObjects.SegCell.update().
void simulationObjects.SegCell.prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
this simulation does not require the inherited prepare to update method
Definition at line 88 of file SegCell.java.
void simulationObjects.SegCell.setState (int state)
Definition at line 93 of file SegCell.java.
References controller.GridInfo.getColor(), simulationObjects.Cell.infoSheet, and simulationObjects.Cell.myState.
void simulationObjects.SegCell.update (Patch currentPatch, List< Patch > neighbors)
make changes to the cells position, if needed
Definition at line 106 of file SegCell.java.
References simulationObjects.Patch.addCell(), simulationObjects.Patch.getRandomEmptyPatch(), simulationObjects.SegCell.isSatisfied(), and simulationObjects.Patch.removeCell().
Member Data Documentation
final int simulationObjects.SegCell.STATE_O = 2 static private
Definition at line 18 of file SegCell.java.
Referenced by simulationObjects.SegCell.getNextState().
final int simulationObjects.SegCell.STATE_X = 1 static private
Definition at line 17 of file SegCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/SegCell.java