cellsociety_team04: simulationObjects.PatchBody Class Reference
simulationObjects.PatchBody Class Reference abstract
Public Member Functions
PatchBody (int x, int y)
abstract void buildBody ()
void createPolyFromPoints (Double[] pts)
Point getCenter ()
int getPatchHeight ()
int getPatchWidth ()
void setCenter (Point c)
void setPatchHeight (int h)
void setPatchWidth (int w)
Public Attributes
int myX
int myY
Protected Attributes
GridInfo infoSheet = new GridInfo()
Private Attributes
int myPatchHeight
int myPatchWidth
Point myCenter
Static Private Attributes
static final double STROKE_WIDTH = .5
Detailed Description
Abstract class for the graphical representation of the patch
Author
Davis
Definition at line 16 of file PatchBody.java.
Constructor & Destructor Documentation
simulationObjects.PatchBody.PatchBody (int x, int y)
Definition at line 26 of file PatchBody.java.
Member Function Documentation
abstract void simulationObjects.PatchBody.buildBody () abstract
calculate the points needed for the specific polygon given our height, width, grid x, and grid y
void simulationObjects.PatchBody.createPolyFromPoints (Double[] pts)
create a polygon given an array of points
Parameters
pts array of x and y points used to create the polygon
Definition at line 44 of file PatchBody.java.
Referenced by simulationObjects.PatchBodyRectangle.buildBody(), simulationObjects.PatchBodyTriangle.buildBody(), and simulationObjects.PatchBodyHexagon.buildBody().
Point simulationObjects.PatchBody.getCenter ()
Definition at line 51 of file PatchBody.java.
References simulationObjects.PatchBody.myCenter.
Referenced by simulationObjects.Patch.updateCellConstraints().
int simulationObjects.PatchBody.getPatchHeight ()
Definition at line 55 of file PatchBody.java.
References simulationObjects.PatchBody.myPatchHeight.
Referenced by simulationObjects.PatchBodyRectangle.buildBody(), simulationObjects.PatchBodyTriangle.buildBody(), simulationObjects.PatchBodyHexagon.buildBody(), and simulationObjects.Patch.updateCellConstraints().
int simulationObjects.PatchBody.getPatchWidth ()
Definition at line 59 of file PatchBody.java.
References simulationObjects.PatchBody.myPatchWidth.
Referenced by simulationObjects.PatchBodyRectangle.buildBody(), simulationObjects.PatchBodyTriangle.buildBody(), simulationObjects.PatchBodyHexagon.PatchBodyHexagon(), and simulationObjects.Patch.updateCellConstraints().
void simulationObjects.PatchBody.setCenter (Point c)
Definition at line 63 of file PatchBody.java.
Referenced by simulationObjects.PatchBodyRectangle.buildBody(), simulationObjects.PatchBodyTriangle.buildBody(), and simulationObjects.PatchBodyHexagon.buildBody().
void simulationObjects.PatchBody.setPatchHeight (int h)
Definition at line 67 of file PatchBody.java.
Referenced by simulationObjects.PatchBodyHexagon.PatchBodyHexagon(), simulationObjects.PatchBodyRectangle.PatchBodyRectangle(), and simulationObjects.PatchBodyTriangle.PatchBodyTriangle().
void simulationObjects.PatchBody.setPatchWidth (int w)
Definition at line 71 of file PatchBody.java.
Referenced by simulationObjects.PatchBodyHexagon.PatchBodyHexagon(), simulationObjects.PatchBodyRectangle.PatchBodyRectangle(), and simulationObjects.PatchBodyTriangle.PatchBodyTriangle().
Member Data Documentation
GridInfo simulationObjects.PatchBody.infoSheet = new GridInfo() protected
Definition at line 21 of file PatchBody.java.
Point simulationObjects.PatchBody.myCenter private
Definition at line 24 of file PatchBody.java.
Referenced by simulationObjects.PatchBody.getCenter().
int simulationObjects.PatchBody.myPatchHeight private
Definition at line 22 of file PatchBody.java.
Referenced by simulationObjects.PatchBody.getPatchHeight().
int simulationObjects.PatchBody.myPatchWidth private
Definition at line 23 of file PatchBody.java.
Referenced by simulationObjects.PatchBody.getPatchWidth().
int simulationObjects.PatchBody.myX
Definition at line 19 of file PatchBody.java.
Referenced by simulationObjects.PatchBodyRectangle.buildBody(), simulationObjects.PatchBodyTriangle.buildBody(), and simulationObjects.PatchBodyHexagon.buildBody().
int simulationObjects.PatchBody.myY
Definition at line 20 of file PatchBody.java.
Referenced by simulationObjects.PatchBodyRectangle.buildBody(), simulationObjects.PatchBodyTriangle.buildBody(), and simulationObjects.PatchBodyHexagon.buildBody().
final double simulationObjects.PatchBody.STROKE_WIDTH = .5 static private
Definition at line 18 of file PatchBody.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/PatchBody.java