cellsociety_team04: simulationObjects.AntCell Class Reference
simulationObjects.AntCell Class Reference
Public Member Functions
ArrayList< Color > getInitialColors ()
int getNextState ()
int getState ()
List< String > getStateTypes ()
void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
void setState (int state)
void update (Patch currentPatch, List< Patch > neighbors)
Public Member Functions inherited from simulationObjects.Cell
Cell ()
void initialize (int x, int y, int state)
abstract int getState ()
abstract void setState (int state)
abstract void update (Patch currentPatch, List< Patch > neighbors)
abstract void prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
abstract int getNextState ()
int getGridX ()
int getGridY ()
void setX (int x)
void setY (int y)
abstract List< String > getStateTypes ()
abstract List< Color > getInitialColors ()
Private Member Functions
void dropFoodItem ()
void dropFoodPheromones ()
void dropHomePheromones ()
void findFoodSource ()
Patch findMaxPheromoneNeighbor ()
void forage ()
boolean hasFoodItem ()
boolean isAtFoodSource ()
boolean isAtNest ()
void moveTo (Patch destination)
void pickUpFoodItem ()
ArrayList< Patch > processFullNeighbors (ArrayList< Patch > neighbors)
ArrayList< Patch > processNeighbors (ArrayList< Patch > neighbors)
void returnToNest ()
Patch selectLocation (ArrayList< Patch > neighbors)
void setOrientation (Patch destination)
void shiftOrientation (int state)
void topOffPheromones ()
Additional Inherited Members
Protected Attributes inherited from simulationObjects.Cell
GridInfo infoSheet = new GridInfo()
int myX
int myY
int myState
Patch myPatch
List< Integer > myParamList
Detailed Description
Definition at line 12 of file AntCell.java.
Member Function Documentation
void simulationObjects.AntCell.dropFoodItem () private
Definition at line 14 of file AntCell.java.
Referenced by simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.dropFoodPheromones () private
Definition at line 19 of file AntCell.java.
References simulationObjects.AntCell.isAtFoodSource(), and simulationObjects.AntCell.topOffPheromones().
Referenced by simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.dropHomePheromones () private
Definition at line 36 of file AntCell.java.
References simulationObjects.AntCell.isAtNest(), and simulationObjects.AntCell.topOffPheromones().
Referenced by simulationObjects.AntCell.findFoodSource().
void simulationObjects.AntCell.findFoodSource () private
Definition at line 53 of file AntCell.java.
References simulationObjects.AntCell.dropHomePheromones(), simulationObjects.AntCell.isAtFoodSource(), simulationObjects.AntCell.isAtNest(), simulationObjects.AntCell.moveTo(), simulationObjects.AntCell.pickUpFoodItem(), simulationObjects.AntCell.selectLocation(), and simulationObjects.AntCell.setOrientation().
Referenced by simulationObjects.AntCell.forage().
Patch simulationObjects.AntCell.findMaxPheromoneNeighbor () private
Definition at line 78 of file AntCell.java.
Referenced by simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.forage () private
Definition at line 83 of file AntCell.java.
References simulationObjects.AntCell.findFoodSource(), simulationObjects.AntCell.hasFoodItem(), and simulationObjects.AntCell.returnToNest().
Referenced by simulationObjects.AntCell.update().
ArrayList<Color> simulationObjects.AntCell.getInitialColors ()
Definition at line 92 of file AntCell.java.
int simulationObjects.AntCell.getNextState ()
Definition at line 98 of file AntCell.java.
int simulationObjects.AntCell.getState ()
Definition at line 104 of file AntCell.java.
List<String> simulationObjects.AntCell.getStateTypes ()
Definition at line 110 of file AntCell.java.
boolean simulationObjects.AntCell.hasFoodItem () private
Definition at line 115 of file AntCell.java.
Referenced by simulationObjects.AntCell.forage().
boolean simulationObjects.AntCell.isAtFoodSource () private
Definition at line 120 of file AntCell.java.
Referenced by simulationObjects.AntCell.dropFoodPheromones(), simulationObjects.AntCell.findFoodSource(), and simulationObjects.AntCell.returnToNest().
boolean simulationObjects.AntCell.isAtNest () private
Definition at line 125 of file AntCell.java.
Referenced by simulationObjects.AntCell.dropHomePheromones(), simulationObjects.AntCell.findFoodSource(), and simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.moveTo (Patch destination) private
Definition at line 130 of file AntCell.java.
Referenced by simulationObjects.AntCell.findFoodSource(), and simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.pickUpFoodItem () private
Definition at line 135 of file AntCell.java.
Referenced by simulationObjects.AntCell.findFoodSource().
void simulationObjects.AntCell.prepareToUpdate (Patch currentPatch, List< Patch > neighbors)
Definition at line 141 of file AntCell.java.
References simulationObjects.Cell.myPatch.
ArrayList<Patch> simulationObjects.AntCell.processFullNeighbors (ArrayList< Patch > neighbors) private
Definition at line 146 of file AntCell.java.
Referenced by simulationObjects.AntCell.selectLocation().
ArrayList<Patch> simulationObjects.AntCell.processNeighbors (ArrayList< Patch > neighbors) private
Definition at line 151 of file AntCell.java.
Referenced by simulationObjects.AntCell.selectLocation().
void simulationObjects.AntCell.returnToNest () private
Definition at line 156 of file AntCell.java.
References simulationObjects.AntCell.dropFoodItem(), simulationObjects.AntCell.dropFoodPheromones(), simulationObjects.AntCell.findMaxPheromoneNeighbor(), simulationObjects.Patch.getState(), simulationObjects.AntCell.isAtFoodSource(), simulationObjects.AntCell.isAtNest(), simulationObjects.AntCell.moveTo(), simulationObjects.Cell.myPatch, simulationObjects.AntCell.setOrientation(), and simulationObjects.AntCell.shiftOrientation().
Referenced by simulationObjects.AntCell.forage().
Patch simulationObjects.AntCell.selectLocation (ArrayList< Patch > neighbors) private
Definition at line 180 of file AntCell.java.
References simulationObjects.AntCell.processFullNeighbors(), and simulationObjects.AntCell.processNeighbors().
Referenced by simulationObjects.AntCell.findFoodSource().
void simulationObjects.AntCell.setOrientation (Patch destination) private
Definition at line 196 of file AntCell.java.
Referenced by simulationObjects.AntCell.findFoodSource(), and simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.setState (int state)
Definition at line 202 of file AntCell.java.
void simulationObjects.AntCell.shiftOrientation (int state) private
Definition at line 207 of file AntCell.java.
Referenced by simulationObjects.AntCell.returnToNest().
void simulationObjects.AntCell.topOffPheromones () private
Definition at line 212 of file AntCell.java.
Referenced by simulationObjects.AntCell.dropFoodPheromones(), and simulationObjects.AntCell.dropHomePheromones().
void simulationObjects.AntCell.update (Patch currentPatch, List< Patch > neighbors)
Definition at line 218 of file AntCell.java.
References simulationObjects.AntCell.forage().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team04/repository/src/simulationObjects/AntCell.java